const productData = [
  {
    id: 1,
    brand: "Armani",
    name: "Black Fashion Zapda",
    img: "./images/game-1.webp",
    price: 350.00,
    color: "red",
    sale: "30%",
    oldPrice: '$500.00',
    isNew: true,
    isHot: true
  },
  {
    id: 2,
    brand: "Christian Dior",
    name: "Coneco Product Sample",
    img: "./images/WirelessSound.png",
    price: 310.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 3,
    brand: "Dolce & Gabbana",
    name: "Daltex Product Example",
    img: "./images/ipadpink.webp",
    price: 200.00,
    color: "red",
    sale: "20%",
    oldPrice: '$250.00',
    isNew: false,
    isHot: false
  },
  {
    id: 4,
    brand: "Givenchy",
    name: "Dantoex Product Sample",
    img: "./images/1headphones.webp",
    price: 450.00,
    color: "red",
    sale: "10%",
    oldPrice: '$499.00',
    isNew: false,
    isHot: false
  },
  {
    id: 5,
    brand: "Donna Karan",
    name: "Dentotam Product...",
    img: "./images/laptop.webp",
    price: 20.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 6,
    brand: "Armani",
    name: "Donkix Product Sample",
    img: "./images/blueiphone.webp",
    price: 60.00,
    color: "red",
    sale: "25%",
    oldPrice: '$100.00',
    isNew: false,
    isHot: false
  },
  {
    id: 7,
    brand: "Christian Dior",
    name: "Finity Product Sample",
    img: "./images/printer.webp",
    price: 90.00,
    color: "red",
    sale: "25%",
    oldPrice: '$12.00',
    isNew: false,
    isHot: false
  },
  {
    id: 8,
    brand: "Dolce & Gabbana",
    name: "Fixair Product Sample",
    img: "./images/ipad.webp",
    price: 210.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 9,
    brand: "Donna Karan",
    name: "Freecof Product Sample",
    img: "./images/apptablet.webp",
    price: "Sold out",
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 10,
    brand: "Armani",
    name: "Freshkix Product Sample",
    img: "./images/lgphone.webp",
    price: 120.00,
    color: "red",
    sale: "20%",
    oldPrice: '$150.00',
    isNew: false,
    isHot: false
  },
  {
    id: 11,
    brand: "Bulgari",
    name: "Georgeous White Bag",
    img: "./images/blueiphone.webp",
    price: 150.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 12,
    brand: "Donna Karan",
    name: "Georgeous White",
    img: "./images/oneplus.webp",
    price: 350.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 13,
    brand: "Dolce & Gabanna",
    name: "Gold Diamond Chain",
    img: "./images/watchsmart.webp",
    price: 399.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 14,
    brand: "Christian Dior",
    name: "Golddax Product Sample",
    img: "./images/samsung.webp",
    price: 120.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 15,
    brand: "Givenchy",
    name: "Hot Com Product Sample",
    img: "./images/macpro.webp",
    price: 225.00,
    color: "red",
    sale: "10%",
    oldPrice: '$250.00',
    isNew: false,
    isHot: false
  },
  {
    id: 16,
    brand: "Bulgari",
    name: "Hotex Product Sample",
    img: "./images/ipad.webp",
    price: 70.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 17,
    brand: "Armani",
    name: "Irene Royal Product",
    img: "./images/camera2.webp",
    price: 150.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 18,
    brand: "Bulgari",
    name: "Kaydex Product Sample",
    img: "./images/airpods.webp",
    price: 450.00,
    color: "red",
    sale: "10%",
    oldPrice: '$500.00',
    isNew: false,
    isHot: false
  },
  {
    id: 19,
    brand: "Donna Karan",
    name: "Kelend Product Sample",
    img: "./images/oneplus.webp",
    price: 330.00,
    color: "red",
    sale: "18%",
    oldPrice: '$400.00',
    isNew: false,
    isHot: false
  },
  {
    id: 20,
    brand: "Donna Karan",
    name: "Kinairer Product Sample",
    img: "./images/product5.webp",
    price: 320.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 21,
    brand: "Givenchy",
    name: "Kinla Product Sample",
    img: "./images/goldiphone.webp",
    price: 120.00,
    color: "red",
    sale: "34%",
    oldPrice: '$229.00',
    isNew: false,
    isHot: false
  },
  {
    id: 22,
    brand: "Givenchy",
    name: "Lamlex Product Sample",
    img: "./images/asuslap.webp",
    price: 150.00,
    color: "red",
    sale: "25%",
    oldPrice: '$200.00',
    isNew: false,
    isHot: false
  },
  {
    id: 23,
    brand: "Christian Dior",
    name: "Lexiited Product Sample",
    img: "./images/watchsmart.webp",
    price: 200.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 24,
    brand: "Christian Dior",
    name: "Lexiwarm Product...",
    img: "./images/oneplus.webp",
    price: 35.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 25,
    brand: "Dolce & Gabanna",
    name: "Lexizimin Product Sample",
    img: "./images/laptop.webp",
    price: 120.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 26,
    brand: "Dolce & Gabanna",
    name: "Newity Product Sample",
    img: "./images/ipadgreen.webp",
    price: 80.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  },
  {
    id: 27,
    brand: "Armani",
    name: "Soltone Product Sample",
    img: "./images/printer.webp",
    price: 280.00,
    color: "black",
    sale: "",
    oldPrice: "",
    isNew: false,
    isHot: false
  }
];